import { reveal } from '../../diagrams/motion';
import { plottedValueText } from '../kits/plots';
import type { ExpansionKitPose } from '../scene-types';
import type { ExpansionBasis, ExpansionRational } from '../value-types';
import type { ProbabilityBaseUpdateScene } from './base-update-types';

/** No membership, sampling or posterior is generated by animation. */
export function baseUpdatePose(t: number, scene: ProbabilityBaseUpdateScene): ExpansionKitPose {
  const beats = [scene.setupAt, scene.actionAt, scene.responseAt, scene.checkAt, scene.resolveAt];
  const values = beats.map((at, i) =>
    reveal(t, at, Math.min(0.25, i < 4 ? beats[i + 1] - at : 0.1)),
  );
  return {
    reveal: values[0],
    action: values[1],
    response: values[2],
    check: values[3],
    resolve: values[4],
  };
}
export const exactProbability = (v: ExpansionRational): string =>
  v.denominator === 1 ? String(v.numerator) : `${v.numerator}/${v.denominator}`;
export function probabilityBasis(b: ExpansionBasis): string {
  return `${b.unit} · ${b.population} · ${b.period}${b.denominator ? ` · denominator ${exactProbability(b.denominator)}` : ''}`;
}
export interface ProbabilityTextRow {
  readonly id: string;
  readonly lines: readonly string[];
}
/** One shared planar ledger, retaining the entire source notation and qualifications. */
export function baseUpdateRows(scene: ProbabilityBaseUpdateScene): readonly ProbabilityTextRow[] {
  return scene.records.map(({ id, role, actorId, populationId, quantity: q }) => ({
    id,
    lines: [
      `${role} · ${q.actor}: ${plottedValueText(q)} · ${q.state}`,
      q.claim,
      probabilityBasis(q.basis),
      q.state === 'conditional' ? q.condition : 'qualifier' in q ? q.qualifier : '',
      `actor ${actorId} · population ${populationId} · source words ${q.evidence.fromWord}–${q.evidence.toWord}`,
    ].filter(Boolean),
  }));
}
export function baseUpdateResultLines(scene: ProbabilityBaseUpdateScene): readonly string[] {
  if (scene.storyId === '09')
    return [
      `Base rate: ${scene.status}`,
      ...scene.derivations.flatMap((d) => [
        `${d.role}: ${d.numeratorRecordId} / ${d.denominatorRecordId}`,
        `${d.value.operands.map(exactProbability).join(' / ')} = ${exactProbability(d.value.result)} · derived`,
        probabilityBasis(d.value.basis),
      ]),
    ];
  if (scene.update.state === 'unresolved')
    return ['Posterior unresolved · source-qualified, not certainty'];
  if (scene.update.state === 'source-stated')
    return [`Posterior source-stated: ${scene.update.posteriorRecordId} · not certainty`];
  const d = scene.update.derivation;
  return [
    `Posterior derived · not certainty`,
    `Supplied prior ${exactProbability(d.supplied.prior)}; likelihood H ${exactProbability(d.supplied.likelihoodHypothesis)}; likelihood complement ${exactProbability(d.supplied.likelihoodComplement)}`,
    `Validated complement prior ${exactProbability(d.complementPrior)}`,
    `Validated ratio (${exactProbability(d.value.operands[0])}) / (${exactProbability(d.value.operands[1])}) = ${exactProbability(d.value.result)}`,
    probabilityBasis(d.value.basis),
  ];
}
/** Fixed authored text boxes; line splitting is lossless, including unbroken maximum labels. */
export function probabilityTextLines(text: string, columns = 100): readonly string[] {
  const chars = Array.from(text);
  return Array.from({ length: Math.ceil(chars.length / columns) }, (_, i) =>
    chars.slice(i * columns, (i + 1) * columns).join(''),
  );
}
export const BASE_UPDATE_LEDGER = { x: 264, y: 10, width: 678, height: 452 } as const;
export const BASE_UPDATE_RESULT = BASE_UPDATE_LEDGER;
export const PROBABILITY_SOURCE_FONT = 22;
export const PROBABILITY_PAGE_COLUMNS = 28;
export const PROBABILITY_PAGE_LINES = 10;
export interface ProbabilityFocusPage {
  readonly recordId?: string;
  readonly actorId?: string;
  readonly populationId?: string;
  readonly context: readonly string[];
  readonly lines: readonly string[];
}
/** Source text is split losslessly, never shortened, squeezed or numerically rounded. */
export function baseUpdatePages(
  scene: ProbabilityBaseUpdateScene,
): readonly ProbabilityFocusPage[] {
  const pages: ProbabilityFocusPage[] = [];
  for (const [index, row] of baseUpdateRows(scene).entries()) {
    const record = scene.records[index];
    const lines = row.lines.flatMap((text) => probabilityTextLines(text, PROBABILITY_PAGE_COLUMNS));
    for (let from = 0; from < lines.length; from += PROBABILITY_PAGE_LINES) {
      pages.push({
        recordId: record.id,
        actorId: record.actorId,
        populationId: record.populationId,
        context: [record.quantity.actor, record.quantity.state],
        lines: lines.slice(from, from + PROBABILITY_PAGE_LINES),
      });
    }
  }
  const result = baseUpdateResultLines(scene).flatMap((text) =>
    probabilityTextLines(text, PROBABILITY_PAGE_COLUMNS),
  );
  const context =
    scene.storyId === '09' ? ['Base rate', scene.status] : ['Posterior', scene.update.state];
  for (let from = 0; from < result.length; from += PROBABILITY_PAGE_LINES) {
    pages.push({ context, lines: result.slice(from, from + PROBABILITY_PAGE_LINES) });
  }
  // A bounded terminal summary is held, rather than continuing to cycle during the final hold.
  const summary =
    scene.storyId === '09'
      ? [
          `Base rate: ${scene.status}`,
          ...scene.derivations.map((d) => `${d.role}: ${exactProbability(d.value.result)} derived`),
        ]
      : scene.update.state === 'derived'
        ? [
            `Posterior: ${exactProbability(scene.update.derivation.value.result)} derived`,
            'Source-qualified, not certainty',
          ]
        : scene.update.state === 'source-stated'
          ? [
              `Posterior source-stated`,
              scene.update.posteriorRecordId,
              'Source-qualified, not certainty',
            ]
          : ['Posterior unresolved', 'Source-qualified, not certainty'];
  pages.push({
    context,
    lines: summary.flatMap((text) => probabilityTextLines(text, PROBABILITY_PAGE_COLUMNS)),
  });
  return pages;
}
/** Real frame-driven controller: records before check, validated outcomes at/after check. */
export function baseUpdatePageIndex(t: number, scene: ProbabilityBaseUpdateScene): number {
  const pages = baseUpdatePages(scene);
  if (!Number.isFinite(t) || t <= scene.setupAt) return 0;
  const firstResult = pages.findIndex((page) => !page.recordId);
  if (t < scene.checkAt) {
    return Math.min(
      firstResult - 1,
      Math.floor(((t - scene.setupAt) / (scene.checkAt - scene.setupAt)) * firstResult),
    );
  }
  if (t >= scene.resolveAt) return pages.length - 1;
  const results = pages.length - firstResult - 1;
  return (
    firstResult +
    Math.min(
      results - 1,
      Math.floor(((t - scene.checkAt) / (scene.resolveAt - scene.checkAt)) * results),
    )
  );
}
export function baseUpdateFocus(
  t: number,
  scene: ProbabilityBaseUpdateScene,
): ProbabilityFocusPage {
  return baseUpdatePages(scene)[baseUpdatePageIndex(t, scene)];
}
