import type {
  WordTimestamp,
  SegmentTimestamp,
  TranscriptionResult,
  CropRegion,
  CropTimelineEntry,
  CropRegionSource,
  TargetDuration,
  ClipEndMode,
  CaptionAnimation,
  CaptionStyleSchema,
  WordAnimationType,
  TextCase,
  CaptionShadowStyle,
  CaptionBackgroundBox,
  CaptionEmphasisStyle,
  CaptionSupersizeStyle,
  OutputAspectRatio,
  ZoomIntensity,
  ZoomMode,
  HookTitleStyle,
  RehookStyle,
  ScoredSegment,
  ScoringResult,
  ScoringProgress,
  FaceDetectionProgress,
  CuriosityGap,
  ClipBoundary,
  CuriosityClipCandidate,
  ShotBreakReason,
  ShotSegment,
  ShotSegmentationResult,
} from '@shared/types'

// Re-export shared types so existing component imports from store don't break
export type {
  WordTimestamp,
  SegmentTimestamp,
  TranscriptionResult,
  CropRegion,
  CropTimelineEntry,
  CropRegionSource,
  TargetDuration,
  ClipEndMode,
  CaptionAnimation,
  CaptionStyleSchema,
  WordAnimationType,
  TextCase,
  CaptionShadowStyle,
  CaptionBackgroundBox,
  CaptionEmphasisStyle,
  CaptionSupersizeStyle,
  OutputAspectRatio,
  ZoomIntensity,
  ZoomMode,
  HookTitleStyle,
  RehookStyle,
  ScoredSegment,
  ScoringResult,
  ScoringProgress,
  FaceDetectionProgress,
  CuriosityGap,
  ClipBoundary,
  CuriosityClipCandidate,
  ShotBreakReason,
  ShotSegment,
  ShotSegmentationResult,
}

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface SourceVideo {
  id: string
  path: string
  name: string
  duration: number
  width: number
  height: number
  thumbnail?: string
  origin: 'file' | 'youtube'
  youtubeUrl?: string
}

/** Extends the shared TranscriptionResult with the pre-formatted AI transcript. */
export interface TranscriptionData extends TranscriptionResult {
  formattedForAI: string
}

export interface PartInfoUI {
  arcId: string
  partNumber: number
  totalParts: number
  partTitle: string
  endCardText: string
}

/**
 * Per-clip render setting overrides.
 * Each key is either `true` (force on), `false` (force off), or absent (use global).
 */
export interface ClipRenderSettings {
  enableCaptions?: boolean
  enableHookTitle?: boolean
  enableAutoZoom?: boolean
  /** 'default' = face-centred crop; 'blur-background' = letterboxed with blurred background */
  layout?: 'default' | 'blur-background'
  /**
   * Per-clip accent color (CSS hex, e.g. '#FF6B35').
   * When set, overrides highlight/emphasis colors in captions, hook title
   * text color, and rehook text color — painting the whole edit with one colour.
   */
  accentColor?: string
}

export interface ClipCandidate {
  id: string
  sourceId: string
  startTime: number
  endTime: number
  duration: number
  text: string
  score: number
  /** The score assigned by the initial AI scoring pass — never overwritten after first set. */
  originalScore?: number
  hookText: string
  reasoning: string
  status: 'pending' | 'approved' | 'rejected'
  cropRegion?: CropRegion
  /**
   * Per-scene crops in source-video absolute seconds. Produced by face
   * detection when PySceneDetect finds more than one scene inside the clip.
   */
  cropTimeline?: CropTimelineEntry[]
  /** Who set the crop — 'auto' (face detection) or 'manual' (user drag). */
  cropRegionSource?: CropRegionSource
  thumbnail?: string
  customThumbnail?: string
  wordTimestamps?: WordTimestamp[]
  loopScore?: number
  loopStrategy?: string
  loopOptimized?: boolean
  crossfadeDuration?: number
  partInfo?: PartInfoUI
  /** Per-clip render overrides — take precedence over global settings at render time. */
  overrides?: ClipRenderSettings
  /** Original AI-selected start/end — set once in setClips, never overwritten. */
  aiStartTime?: number
  aiEndTime?: number
  /** AI Edit Plan for this clip. Generated by a single Gemini call. */
  aiEditPlan?: import('@shared/types').AIEditPlan
  /** Shot segmentation — breaks this clip into 4-6 second "shots" at natural break points. */
  shots?: import('@shared/types').ShotSegment[]
  /** Per-shot style assignments — maps each shot to a style preset ID. */
  shotStyles?: import('@shared/types').ShotStyleAssignment[]
  /** Detected filler segments for this clip (absolute timestamps from source) */
  fillerSegments?: FillerSegmentUI[]
  /** Indices of filler segments the user has restored (won't be cut) */
  restoredFillerIndices?: number[]
  /** Time saved by filler removal (seconds) */
  fillerTimeSaved?: number
  /** Face-tracking timeline for animated crop. */
  faceTimeline?: Array<{ t: number; x: number; y: number; w: number; h: number }>
}

/** Filler segment as stored in the renderer — mirrors the main-process FillerSegment type. */
export interface FillerSegmentUI {
  start: number
  end: number
  type: 'filler' | 'silence' | 'repeat'
  label: string
}

export type PipelineStage =
  | 'idle'
  | 'downloading'
  | 'transcribing'
  | 'scoring'
  | 'optimizing-loops'
  | 'detecting-faces'
  | 'ai-editing'
  | 'segmenting'
  | 'ready'
  | 'rendering'
  | 'done'
  | 'error'

export interface PipelineProgress {
  stage: PipelineStage
  message: string
  percent: number
}

export interface RenderProgress {
  clipId: string
  percent: number
  status: 'queued' | 'preparing' | 'rendering' | 'done' | 'error'
  error?: string
  outputPath?: string
  /** FFmpeg command string captured at render time (populated on error, or always in developer mode). */
  ffmpegCommand?: string
  /** Message shown during the prepare phase (B-Roll generation, filler removal, etc.) */
  prepareMessage?: string
}

export interface ZoomSettings {
  enabled: boolean
  mode: ZoomMode
  intensity: ZoomIntensity
  intervalSeconds: number
}

export interface HookTitleOverlaySettings {
  enabled: boolean
  style: HookTitleStyle
  displayDuration: number
  fadeIn: number
  fadeOut: number
  fontSize: number
  textColor: string
  outlineColor: string
  outlineWidth: number
}

/** Settings for the mid-clip re-hook / pattern interrupt text overlay. */
export interface RehookOverlaySettings {
  enabled: boolean
  style: RehookStyle
  displayDuration: number
  fadeIn: number
  fadeOut: number
  positionFraction: number
}

export interface BRollSettings {
  enabled: boolean
  intervalSeconds: number
  clipDuration: number
  displayMode: BRollDisplayMode
  transition: BRollTransition
  pipSize: number
  pipPosition: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'
}

export type BRollDisplayMode = 'fullscreen' | 'split-top' | 'split-bottom' | 'pip'
export type BRollTransition = 'hard-cut' | 'crossfade' | 'swipe-up' | 'swipe-down'

export interface FillerRemovalSettings {
  enabled: boolean
  removeFillerWords: boolean
  trimSilences: boolean
  removeRepeats: boolean
  silenceThreshold: number
  fillerWords: string[]
}

export type RenderQualityPreset = 'draft' | 'normal' | 'high' | 'custom'
export type OutputResolution = '1080x1920' | '720x1280' | '540x960'
export type OutputFormat = 'mp4' | 'webm'
export type EncodingPreset = 'ultrafast' | 'veryfast' | 'medium' | 'slow'

export interface RenderQualitySettings {
  preset: RenderQualityPreset
  customCrf: number
  outputResolution: OutputResolution
  outputFormat: OutputFormat
  encodingPreset: EncodingPreset
}

export interface AppSettings {
  geminiApiKey: string
  /** fal.ai API key for AI-generated B-roll images. */
  falApiKey: string
  outputDirectory: string | null
  minScore: number
  autoZoom: ZoomSettings
  hookTitleOverlay: HookTitleOverlaySettings
  rehookOverlay: RehookOverlaySettings
  broll: BRollSettings
  fillerRemoval: FillerRemovalSettings
  enableNotifications: boolean
  /** When true, all FFmpeg commands are logged to the error log during rendering. */
  developerMode: boolean
  renderQuality: RenderQualitySettings
  outputAspectRatio: OutputAspectRatio
  /** Template for rendered clip filenames. */
  filenameTemplate: string
  /** Number of clips to render in parallel (1–4). */
  renderConcurrency: number
}

export interface ProcessingConfig {
  targetDuration: TargetDuration
  enablePerfectLoop: boolean
  clipEndMode: ClipEndMode
  enableMultiPart: boolean
  /** Run the AI edit orchestrator after scoring — generates word emphasis, B-Roll, and SFX plans for every clip. */
  enableAiEdit: boolean
  /** Target audience description used to filter clips for relevance. */
  targetAudience: string
}

export interface ErrorLogEntry {
  id: string
  timestamp: number
  source: string
  message: string
  /** Optional extra detail (e.g. FFmpeg command string) shown in an expandable section. */
  details?: string
}

export type PythonSetupState = 'checking' | 'not-setup' | 'installing' | 'ready' | 'skipped' | 'error'

// ---------------------------------------------------------------------------
// Full AppState
// ---------------------------------------------------------------------------

export interface AppState {
  // Source videos
  sources: SourceVideo[]
  activeSourceId: string | null

  // Transcriptions (keyed by source ID)
  transcriptions: Record<string, TranscriptionData>

  // Clip candidates (keyed by source ID)
  clips: Record<string, ClipCandidate[]>

  // Pipeline
  pipeline: PipelineProgress
  /** Which pipeline stage failed (enables "Retry from stage" UI). */
  failedPipelineStage: PipelineStage | null
  /** Stages that completed successfully — used to skip them on retry. */
  completedPipelineStages: Set<PipelineStage>
  /** Cached sourcePath from download step — avoids re-downloading on retry. */
  cachedSourcePath: string | null

  // Render
  renderProgress: RenderProgress[]
  isRendering: boolean
  activeEncoder: { encoder: string; isHardware: boolean } | null
  renderStartedAt: number | null
  renderCompletedAt: number | null
  clipRenderTimes: Record<string, { started: number; completed: number; duration: number }>
  /** Per-clip render error messages, keyed by clipId. */
  renderErrors: Record<string, string>

  // Single-clip render
  singleRenderClipId: string | null
  singleRenderProgress: number
  singleRenderStatus: 'idle' | 'rendering' | 'done' | 'error'
  singleRenderOutputPath: string | null
  singleRenderError: string | null

  // Settings
  settings: AppSettings

  // Python setup
  pythonStatus: PythonSetupState
  pythonSetupError: string | null
  pythonSetupProgress: {
    stage: string
    message: string
    percent: number
    package?: string
    currentPackage?: number
    totalPackages?: number
  } | null

  // Processing config
  processingConfig: ProcessingConfig

  // Errors
  errorLog: ErrorLogEntry[]

  // Clip selection (keyboard navigation)
  selectedClipIndex: number

  // Undo / Redo — global (batch operations)
  _undoStack: import('./history-slice').UndoableSnapshot[]
  _redoStack: import('./history-slice').UndoableSnapshot[]
  canUndo: boolean
  canRedo: boolean
  undo: () => void
  redo: () => void

  // Undo / Redo — per-clip (edit actions)
  _clipUndoStacks: Record<string, import('./history-slice').ClipUndoEntry[]>
  _clipRedoStacks: Record<string, import('./history-slice').ClipUndoEntry[]>
  /** ID of the most recently edited clip — used to target keyboard undo/redo. */
  _lastEditedClipId: string | null
  _lastEditedSourceId: string | null
  canUndoClip: (clipId: string) => boolean
  canRedoClip: (clipId: string) => boolean
  undoClip: (sourceId: string, clipId: string) => void
  redoClip: (sourceId: string, clipId: string) => void
  clearClipUndoHistory: (clipId: string) => void

  // Actions — Sources
  addSource: (source: SourceVideo) => void
  removeSource: (id: string) => void
  setActiveSource: (id: string | null) => void

  // Actions — Transcription
  setTranscription: (sourceId: string, data: TranscriptionData) => void

  // Actions — Clips
  setClips: (sourceId: string, clips: ClipCandidate[]) => void
  updateClipStatus: (sourceId: string, clipId: string, status: ClipCandidate['status']) => void
  updateClipTrim: (
    sourceId: string,
    clipId: string,
    startTime: number,
    endTime: number
  ) => void
  updateClipThumbnail: (sourceId: string, clipId: string, thumbnail: string) => void
  setClipCustomThumbnail: (sourceId: string, clipId: string, thumbnail: string | null) => void
  updateClipCrop: (
    sourceId: string,
    clipId: string,
    crop: CropRegion,
    opts?: { timeline?: CropTimelineEntry[]; source?: CropRegionSource }
  ) => void
  /** User manually dragged the crop — sets cropRegion, clears timeline, marks manual. */
  setClipManualCrop: (sourceId: string, clipId: string, crop: CropRegion) => void
  /** Clear the manual flag so the next face-detection pass can re-populate. */
  resetClipCropSource: (sourceId: string, clipId: string) => void
  updateClipHookText: (sourceId: string, clipId: string, hookText: string) => void
  updateClipLoop: (sourceId: string, clipId: string, loopData: { loopScore: number; loopStrategy: string; loopOptimized: boolean; crossfadeDuration?: number }) => void
  setClipPartInfo: (sourceId: string, clipId: string, partInfo: PartInfoUI) => void
  setClipOverride: (sourceId: string, clipId: string, key: keyof ClipRenderSettings, value: ClipRenderSettings[keyof ClipRenderSettings]) => void
  clearClipOverrides: (sourceId: string, clipId: string) => void
  resetClipBoundaries: (sourceId: string, clipId: string) => void
  rescoreClip: (sourceId: string, clipId: string, newScore: number, newReasoning: string, newHookText?: string) => void
  setClipAIEditPlan: (sourceId: string, clipId: string, plan: import('@shared/types').AIEditPlan) => void
  clearClipAIEditPlan: (sourceId: string, clipId: string) => void
  setClipShots: (sourceId: string, clipId: string, shots: import('@shared/types').ShotSegment[]) => void
  clearClipShots: (sourceId: string, clipId: string) => void
  setShotStyle: (sourceId: string, clipId: string, shotIndex: number, presetId: string) => void
  clearShotStyle: (sourceId: string, clipId: string, shotIndex: number) => void
  setClipShotStyles: (sourceId: string, clipId: string, assignments: import('@shared/types').ShotStyleAssignment[]) => void
  clearAllShotStyles: (sourceId: string, clipId: string) => void
  setClipFillers: (sourceId: string, clipId: string, segments: FillerSegmentUI[], timeSaved: number) => void
  toggleFillerRestore: (sourceId: string, clipId: string, segmentIndex: number) => void
  clearClipFillers: (sourceId: string, clipId: string) => void
  approveAll: (sourceId: string) => void
  approveClipsAboveScore: (sourceId: string, minScore: number) => { approved: number; rejected: number }
  rejectAll: (sourceId: string) => void
  setSelectedClipIndex: (index: number) => void

  // Actions — Batch multi-select
  selectedClipIds: Set<string>
  toggleClipSelection: (clipId: string) => void
  selectAllVisible: (clipIds: string[]) => void
  clearSelection: () => void
  batchUpdateClips: (sourceId: string, clipIds: string[], updates: Partial<Pick<ClipCandidate, 'status'> & { trimOffsetSeconds: number; overrides: Partial<ClipRenderSettings> }>) => void

  // Actions — Pipeline
  setPipeline: (progress: PipelineProgress) => void
  setFailedPipelineStage: (stage: PipelineStage) => void
  setCachedSourcePath: (path: string) => void
  markStageCompleted: (stage: PipelineStage) => void
  clearPipelineCache: () => void

  // Actions — Render
  setRenderProgress: (progress: RenderProgress[]) => void
  setIsRendering: (rendering: boolean) => void
  setRenderError: (clipId: string, error: string) => void
  clearRenderErrors: () => void
  setSingleRenderState: (patch: {
    clipId?: string | null
    progress?: number
    status?: 'idle' | 'rendering' | 'done' | 'error'
    outputPath?: string | null
    error?: string | null
  }) => void

  // Actions — Settings
  setGeminiApiKey: (key: string) => void
  setFalApiKey: (key: string) => void
  setOutputDirectory: (dir: string) => void
  setMinScore: (score: number) => void
  setAutoZoomEnabled: (enabled: boolean) => void
  setAutoZoomMode: (mode: ZoomMode) => void
  setAutoZoomIntensity: (intensity: ZoomIntensity) => void
  setAutoZoomInterval: (seconds: number) => void

  // Actions — Hook Title Overlay
  setHookTitleEnabled: (enabled: boolean) => void
  setHookTitleStyle: (style: HookTitleStyle) => void
  setHookTitleDisplayDuration: (seconds: number) => void
  setHookTitleFontSize: (px: number) => void
  setHookTitleTextColor: (color: string) => void
  setHookTitleOutlineColor: (color: string) => void
  setHookTitleOutlineWidth: (px: number) => void
  setHookTitleFadeIn: (seconds: number) => void
  setHookTitleFadeOut: (seconds: number) => void

  // Actions — Re-hook Overlay
  setRehookEnabled: (enabled: boolean) => void
  setRehookStyle: (style: RehookStyle) => void
  setRehookDisplayDuration: (seconds: number) => void
  setRehookPositionFraction: (fraction: number) => void

  // Actions — B-Roll
  setBRollEnabled: (enabled: boolean) => void
  setBRollIntervalSeconds: (seconds: number) => void
  setBRollClipDuration: (seconds: number) => void
  setBRollDisplayMode: (mode: BRollDisplayMode) => void
  setBRollTransition: (transition: BRollTransition) => void
  setBRollPipSize: (size: number) => void
  setBRollPipPosition: (position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right') => void

  // Actions — Filler Removal
  setFillerRemovalEnabled: (enabled: boolean) => void
  setFillerRemovalFillerWords: (enabled: boolean) => void
  setFillerRemovalSilences: (enabled: boolean) => void
  setFillerRemovalRepeats: (enabled: boolean) => void
  setFillerRemovalSilenceThreshold: (seconds: number) => void
  setFillerRemovalWordList: (words: string[]) => void

  // Actions — Notifications
  setEnableNotifications: (enabled: boolean) => void

  // Actions — Developer Mode
  setDeveloperMode: (enabled: boolean) => void

  // Actions — Render Quality
  setRenderQuality: (quality: Partial<RenderQualitySettings>) => void
  setOutputAspectRatio: (ratio: OutputAspectRatio) => void
  setFilenameTemplate: (template: string) => void
  setRenderConcurrency: (concurrency: number) => void

  // Actions — Reset
  resetSettings: () => void
  resetSection: (section: 'autoZoom' | 'hookTitle' | 'rehook' | 'fillerRemoval' | 'broll' | 'aiSettings' | 'renderQuality') => void

  // Actions — Python setup
  setPythonStatus: (status: PythonSetupState) => void
  setPythonSetupError: (error: string | null) => void
  setPythonSetupProgress: (progress: {
    stage: string
    message: string
    percent: number
    package?: string
    currentPackage?: number
    totalPackages?: number
  } | null) => void

  // Actions — Processing Config
  setProcessingConfig: (config: Partial<ProcessingConfig>) => void
  resetProcessingConfig: () => void

  // Network status
  isOnline: boolean
  setIsOnline: (online: boolean) => void

  // Actions — Errors
  addError: (entry: Omit<ErrorLogEntry, 'id' | 'timestamp'>) => void
  clearErrors: () => void

  // Computed
  getApprovedClips: (sourceId: string) => ClipCandidate[]
  getActiveSource: () => SourceVideo | null
  getActiveTranscription: () => TranscriptionData | null
  getActiveClips: () => ClipCandidate[]

  // Dirty state (unsaved changes)
  isDirty: boolean
  lastSavedAt: number | null

  // Project (pure state — persistence lives in services/project-service.ts)
  reset: () => void

  // Theme — locked to 'dark'. No setter.
  theme: 'dark'

  // Recovery acknowledgement (replaces hasCompletedOnboarding)
  acknowledgedRecovery: boolean
  acknowledgeRecovery: () => void

  // AI Token Usage
  aiUsage: {
    totalPromptTokens: number
    totalCompletionTokens: number
    totalCalls: number
    callHistory: Array<{ source: string; promptTokens: number; completionTokens: number; totalTokens: number; model: string; timestamp: number }>
    sessionStarted: number
  }
  trackTokenUsage: (event: { source: string; promptTokens: number; completionTokens: number; totalTokens: number; model: string; timestamp: number }) => void
  resetAiUsage: () => void

  // Secrets hydration (Electron safeStorage)
  hydrateSecretsFromMain: () => Promise<void>
}
