/**
 * Headless render wrapper around @remotion/renderer.
 *
 * Release builds use the browser bundle generated by `npm run build`; development
 * creates the same bundle lazily on first use. Subsequent renders reuse it and
 * only re-launch the headless browser tab.
 *
 * Output: ProRes 4444 .mov with alpha when `transparent: true`, otherwise
 * H.264 .mp4. Segment-render uses the ProRes/.mov path so the result composites
 * cleanly into the FFmpeg timeline.
 */

import { existsSync, mkdirSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { makeCancelSignal, renderMedia, selectComposition } from '@remotion/renderer';
import { app } from 'electron';

let bundlePromise: Promise<string> | null = null;
let remotionWorkingDirectoryConfigured = false;

/**
 * Resolve the development Remotion entry point.
 *
 * Remotion's `bundle()` compiles the composition tree from source via its own
 * webpack pass, so it needs `src/main/remotion/index.ts`, not electron-vite's
 * compiled main-process output. Release builds never bundle from app.asar; they
 * consume the physical prebuilt bundle under `process.resourcesPath/remotion`.
 */
function resolveRemotionEntry(): string {
  const appPath = app.getAppPath();
  const candidates = [
    join(appPath, 'src', 'main', 'remotion', 'index.ts'),
    join(appPath, 'src', 'main', 'remotion', 'index.tsx'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return candidates[0];
}

/** Resolve the development public directory containing `fonts/`. */
function resolveRemotionPublicDir(): string {
  return join(app.getAppPath(), 'resources');
}

function resolvePackagedRemotionBundle(): string {
  const bundlePath = join(process.resourcesPath, 'remotion');
  if (!existsSync(join(bundlePath, 'index.html'))) {
    throw new Error(`Packaged Remotion bundle is missing: ${bundlePath}`);
  }
  return bundlePath;
}

function resolveRemotionBinariesDirectory(): string | null {
  if (!app.isPackaged) return null;

  const packageNames =
    process.platform === 'darwin'
      ? [`compositor-darwin-${process.arch}`]
      : process.platform === 'win32'
        ? [`compositor-win32-${process.arch}-msvc`]
        : [`compositor-linux-${process.arch}-gnu`, `compositor-linux-${process.arch}-musl`];
  const executable = process.platform === 'win32' ? 'remotion.exe' : 'remotion';

  for (const packageName of packageNames) {
    const directory = join(
      process.resourcesPath,
      'app.asar.unpacked',
      'node_modules',
      '@remotion',
      packageName,
    );
    if (existsSync(join(directory, executable))) return directory;
  }

  throw new Error(`Packaged Remotion binaries are missing for ${process.platform}-${process.arch}`);
}

function ensureWritableRemotionWorkingDirectory(): void {
  if (!app.isPackaged || remotionWorkingDirectoryConfigured) return;

  const userDataDirectory = app.getPath('userData');
  mkdirSync(userDataDirectory, { recursive: true });
  process.chdir(userDataDirectory);
  remotionWorkingDirectoryConfigured = true;
}

async function createDevelopmentBundle(): Promise<string> {
  const [{ bundle }, { createWebpackOverride }] = await Promise.all([
    import('@remotion/bundler'),
    import('./webpack-override'),
  ]);
  const projectRoot = app.getAppPath();

  return bundle({
    entryPoint: resolveRemotionEntry(),
    rootDir: projectRoot,
    webpackOverride: createWebpackOverride(projectRoot),
    publicDir: resolveRemotionPublicDir(),
    onProgress: () => undefined,
  });
}

async function getBundle(): Promise<string> {
  if (!bundlePromise) {
    bundlePromise = app.isPackaged
      ? Promise.resolve(resolvePackagedRemotionBundle())
      : createDevelopmentBundle();
  }
  return bundlePromise;
}

export interface RenderRemotionOptions {
  compositionId: string;
  inputProps: Record<string, unknown>;
  /** Duration in seconds. Composition's durationInFrames is overridden. */
  durationSec: number;
  fps: number;
  width: number;
  height: number;
  /** When true, output is ProRes 4444 .mov with alpha. */
  transparent?: boolean;
  /**
   * Output file path. Extension drives format: .mov for transparent, .mp4
   * otherwise. If omitted, a temp path is generated.
   */
  outputPath?: string;
  /**
   * Per-frame render progress callback (RF-006). Receives a 0–1 fraction from
   * Remotion's `renderMedia` so callers can advance a progress bar smoothly
   * during long block renders instead of freezing until the segment finishes.
   */
  onProgress?: ((progress: number) => void) | undefined;
  signal?: AbortSignal;
  /** Limit frame workers for long-form 3D jobs without changing portrait defaults. */
  concurrency?: number;
}

export async function renderRemotionSegment(opts: RenderRemotionOptions): Promise<string> {
  opts.signal?.throwIfAborted();
  ensureWritableRemotionWorkingDirectory();
  const serveUrl = await getBundle();
  opts.signal?.throwIfAborted();
  const binariesDirectory = resolveRemotionBinariesDirectory();

  const composition = await selectComposition({
    serveUrl,
    id: opts.compositionId,
    inputProps: opts.inputProps,
    binariesDirectory,
    timeoutInMilliseconds: 30_000,
  });
  opts.signal?.throwIfAborted();

  const durationInFrames = Math.max(1, Math.round(opts.durationSec * opts.fps));
  const outPath =
    opts.outputPath ??
    join(
      mkdtempSync(join(tmpdir(), 'remotion-seg-')),
      `${opts.compositionId}.${opts.transparent ? 'mov' : 'mp4'}`,
    );

  const { cancelSignal, cancel } = makeCancelSignal();
  opts.signal?.addEventListener('abort', cancel, { once: true });
  try {
    opts.signal?.throwIfAborted();
    await renderMedia({
      serveUrl,
      cancelSignal,
      concurrency: opts.concurrency,
      composition: {
        ...composition,
        durationInFrames,
        fps: opts.fps,
        width: opts.width,
        height: opts.height,
      },
      codec: opts.transparent ? 'prores' : 'h264',
      proResProfile: opts.transparent ? '4444' : undefined,
      // ProRes defaults to yuv420p (no alpha). Without an alpha-carrying pixel
      // format the "transparent" areas bake to black and composite as a black
      // screen behind the overlay. yuva444p10le is the alpha-capable ProRes 4444
      // format; paired with the PNG image format this preserves the alpha channel.
      pixelFormat: opts.transparent ? 'yuva444p10le' : undefined,
      outputLocation: outPath,
      inputProps: opts.inputProps,
      imageFormat: 'png',
      chromiumOptions: { gl: 'angle' },
      binariesDirectory,
      // Forward Remotion's per-frame progress (0..1) so block segments advance
      // the render bar smoothly rather than stalling for the whole encode. The
      // wrapper is always defined (no-ops via optional chaining when the caller
      // passed nothing) to stay clean under exactOptionalPropertyTypes.
      onProgress: ({ progress }) => opts.onProgress?.(progress),
    });
    opts.signal?.throwIfAborted();
    return outPath;
  } finally {
    opts.signal?.removeEventListener('abort', cancel);
  }
}
