/**
 * Headless render wrapper around @remotion/renderer.
 *
 * Release builds use the browser bundle generated by `npm run build`; development
 * creates the same bundle lazily on first use. Subsequent renders reuse it and
 * one shared headless browser; identical renders are served from a disk cache
 * (`render-cache.ts`, disable with BATCHCLIP_DISABLE_RENDER_CACHE=1).
 *
 * Output: ProRes 4444 .mov with alpha when `transparent: true`, otherwise
 * H.264 .mp4. Segment-render uses the ProRes/.mov path so the result composites
 * cleanly into the FFmpeg timeline.
 */

import { existsSync, mkdirSync, mkdtempSync } from 'node:fs';
import { availableParallelism, tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  type HeadlessBrowser,
  makeCancelSignal,
  openBrowser,
  renderMedia,
  selectComposition,
} from '@remotion/renderer';
import { app } from 'electron';
import { getEncoder, isGpuEncoderDisabled } from '../ffmpeg';
import {
  DEFAULT_RENDER_CACHE_MAX_BYTES,
  fingerprintBundle,
  pruneRenderCache,
  remotionCacheKey,
  restoreCachedRender,
  storeCachedRender,
} from './render-cache';

let bundlePromise: Promise<string> | null = null;
let bundleFingerprint: string | null = null;
let remotionWorkingDirectoryConfigured = false;

// One headless Chrome shared by every render in the session. Without it each
// scene launched Chrome twice (selectComposition + renderMedia). It closes
// after a short idle period so it never lingers once an export finishes.
const CHROMIUM_OPTIONS = { gl: 'angle' } as const;
const BROWSER_IDLE_CLOSE_MS = 60_000;
let sharedBrowser: Promise<HeadlessBrowser> | null = null;
let activeRenders = 0;
let idleCloseTimer: NodeJS.Timeout | null = null;
let quitHookRegistered = false;

function acquireBrowser(): Promise<HeadlessBrowser> {
  if (idleCloseTimer) {
    clearTimeout(idleCloseTimer);
    idleCloseTimer = null;
  }
  if (!sharedBrowser) {
    if (!quitHookRegistered) {
      quitHookRegistered = true;
      app.on('will-quit', () => void closeRemotionBrowser());
    }
    const opening = openBrowser('chrome', { chromiumOptions: CHROMIUM_OPTIONS });
    sharedBrowser = opening;
    opening.then(
      (browser) => {
        // A crashed/closed browser must not be handed to the next render.
        browser.on('closed', () => {
          if (sharedBrowser === opening) sharedBrowser = null;
        });
      },
      () => {
        if (sharedBrowser === opening) sharedBrowser = null;
      },
    );
  }
  return sharedBrowser;
}

function scheduleIdleBrowserClose(): void {
  if (activeRenders > 0 || !sharedBrowser) return;
  const browser = sharedBrowser;
  idleCloseTimer = setTimeout(() => {
    idleCloseTimer = null;
    if (activeRenders > 0 || sharedBrowser !== browser) return;
    sharedBrowser = null;
    void closeBrowserQuietly(browser);
  }, BROWSER_IDLE_CLOSE_MS);
  idleCloseTimer.unref();
}

async function closeBrowserQuietly(browser: Promise<HeadlessBrowser>): Promise<void> {
  try {
    await (await browser).close({ silent: true });
  } catch {
    /* already gone */
  }
}

/** Close the shared render browser now (app quit). */
export async function closeRemotionBrowser(): Promise<void> {
  if (idleCloseTimer) clearTimeout(idleCloseTimer);
  idleCloseTimer = null;
  const browser = sharedBrowser;
  sharedBrowser = null;
  if (browser) await closeBrowserQuietly(browser);
}

/**
 * Frame workers per render. Remotion defaults to half the cores per render;
 * when several renders run at once (parallel clip exports) that oversubscribes
 * the CPU, so the default share is split between the concurrent renders.
 */
export function resolveRenderConcurrency(
  requested: number | undefined,
  concurrentRenders: number,
  cpuCount: number,
): number {
  if (requested !== undefined) return requested;
  const defaultShare = Math.round(Math.min(8, Math.max(1, cpuCount / 2)));
  return Math.max(1, Math.floor(defaultShare / Math.max(1, concurrentRenders)));
}

/** GPU H.264 only when the app's own probe found a working GPU encoder. */
function remotionHardwareEncodingAvailable(): boolean {
  if (isGpuEncoderDisabled()) return false;
  const { encoder } = getEncoder();
  if (process.platform === 'darwin') return encoder === 'h264_videotoolbox';
  return encoder === 'h264_nvenc';
}

function renderCacheDir(): string | null {
  if (process.env.BATCHCLIP_DISABLE_RENDER_CACHE === '1') return null;
  return join(app.getPath('userData'), 'render-cache', 'remotion');
}

/**
 * Resolve the development Remotion entry point.
 *
 * Remotion's `bundle()` compiles the composition tree from source via its own
 * webpack pass, so it needs `src/main/remotion/index.ts`, not electron-vite's
 * compiled main-process output. Release builds never bundle from app.asar; they
 * consume the physical prebuilt bundle under `process.resourcesPath/remotion`.
 */
function resolveRemotionEntry(): string {
  const appPath = app.getAppPath();
  const candidates = [
    join(appPath, 'src', 'main', 'remotion', 'index.ts'),
    join(appPath, 'src', 'main', 'remotion', 'index.tsx'),
  ];
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return candidates[0];
}

/** Resolve the development public directory containing `fonts/`. */
function resolveRemotionPublicDir(): string {
  return join(app.getAppPath(), 'resources');
}

function resolvePackagedRemotionBundle(): string {
  const bundlePath = join(process.resourcesPath, 'remotion');
  if (!existsSync(join(bundlePath, 'index.html'))) {
    throw new Error(`Packaged Remotion bundle is missing: ${bundlePath}`);
  }
  return bundlePath;
}

function resolveRemotionBinariesDirectory(): string | null {
  if (!app.isPackaged) return null;

  const packageNames =
    process.platform === 'darwin'
      ? [`compositor-darwin-${process.arch}`]
      : process.platform === 'win32'
        ? [`compositor-win32-${process.arch}-msvc`]
        : [`compositor-linux-${process.arch}-gnu`, `compositor-linux-${process.arch}-musl`];
  const executable = process.platform === 'win32' ? 'remotion.exe' : 'remotion';

  for (const packageName of packageNames) {
    const directory = join(
      process.resourcesPath,
      'app.asar.unpacked',
      'node_modules',
      '@remotion',
      packageName,
    );
    if (existsSync(join(directory, executable))) return directory;
  }

  throw new Error(`Packaged Remotion binaries are missing for ${process.platform}-${process.arch}`);
}

function ensureWritableRemotionWorkingDirectory(): void {
  if (!app.isPackaged || remotionWorkingDirectoryConfigured) return;

  const userDataDirectory = app.getPath('userData');
  mkdirSync(userDataDirectory, { recursive: true });
  process.chdir(userDataDirectory);
  remotionWorkingDirectoryConfigured = true;
}

async function createDevelopmentBundle(): Promise<string> {
  const [{ bundle }, { createWebpackOverride }] = await Promise.all([
    import('@remotion/bundler'),
    import('./webpack-override'),
  ]);
  const projectRoot = app.getAppPath();

  return bundle({
    entryPoint: resolveRemotionEntry(),
    rootDir: projectRoot,
    webpackOverride: createWebpackOverride(projectRoot),
    publicDir: resolveRemotionPublicDir(),
    onProgress: () => undefined,
  });
}

async function getBundle(): Promise<string> {
  if (!bundlePromise) {
    bundlePromise = app.isPackaged
      ? Promise.resolve(resolvePackagedRemotionBundle())
      : createDevelopmentBundle();
  }
  return bundlePromise;
}

function getBundleFingerprint(serveUrl: string): string {
  bundleFingerprint ??= fingerprintBundle(serveUrl);
  return bundleFingerprint;
}

export interface RenderRemotionOptions {
  compositionId: string;
  inputProps: Record<string, unknown>;
  /** Duration in seconds. Composition's durationInFrames is overridden. */
  durationSec: number;
  fps: number;
  width: number;
  height: number;
  /** When true, output is ProRes 4444 .mov with alpha. */
  transparent?: boolean;
  /**
   * Output file path. Extension drives format: .mov for transparent, .mp4
   * otherwise. If omitted, a temp path is generated.
   */
  outputPath?: string;
  /**
   * Per-frame render progress callback (RF-006). Receives a 0–1 fraction from
   * Remotion's `renderMedia` so callers can advance a progress bar smoothly
   * during long block renders instead of freezing until the segment finishes.
   */
  onProgress?: ((progress: number) => void) | undefined;
  signal?: AbortSignal;
  /** Limit frame workers for long-form 3D jobs without changing portrait defaults. */
  concurrency?: number;
}

// Opaque (non-alpha) renders are intermediates re-encoded by FFmpeg later, so
// they use JPEG frames (Remotion: PNG is slower and only needed for alpha) at
// near-lossless quality, and a generous bitrate when encoded on the GPU.
const OPAQUE_JPEG_QUALITY = 95;
const OPAQUE_GPU_BITRATE = '40M';

export async function renderRemotionSegment(opts: RenderRemotionOptions): Promise<string> {
  opts.signal?.throwIfAborted();
  ensureWritableRemotionWorkingDirectory();
  const serveUrl = await getBundle();
  opts.signal?.throwIfAborted();
  const started = Date.now();
  const transparent = opts.transparent === true;
  const durationInFrames = Math.max(1, Math.round(opts.durationSec * opts.fps));
  const outPath =
    opts.outputPath ??
    join(
      mkdtempSync(join(tmpdir(), 'remotion-seg-')),
      `${opts.compositionId}.${transparent ? 'mov' : 'mp4'}`,
    );

  // ── Cache lookup ─────────────────────────────────────────────────────
  const cacheDir = renderCacheDir();
  let cacheKey: string | null = null;
  if (cacheDir) {
    try {
      cacheKey = remotionCacheKey({
        bundleFingerprint: getBundleFingerprint(serveUrl),
        compositionId: opts.compositionId,
        inputProps: opts.inputProps,
        durationInFrames,
        fps: opts.fps,
        width: opts.width,
        height: opts.height,
        transparent,
        encoding: transparent ? 'prores4444/yuva444p10le/png' : 'h264/jpeg95',
      });
      if (restoreCachedRender(cacheDir, cacheKey, outPath)) {
        opts.onProgress?.(1);
        console.log(
          `[Remotion] ${opts.compositionId} cache hit (${opts.durationSec.toFixed(2)}s) in ${Date.now() - started}ms`,
        );
        return outPath;
      }
    } catch (err) {
      console.warn('[Remotion] render cache unavailable, rendering fresh:', err);
      cacheKey = null;
    }
  }

  const binariesDirectory = resolveRemotionBinariesDirectory();
  activeRenders++;
  try {
    const puppeteerInstance = await acquireBrowser();
    opts.signal?.throwIfAborted();
    const composition = await selectComposition({
      serveUrl,
      id: opts.compositionId,
      inputProps: opts.inputProps,
      binariesDirectory,
      puppeteerInstance,
      timeoutInMilliseconds: 30_000,
    });
    opts.signal?.throwIfAborted();

    const concurrency = resolveRenderConcurrency(
      opts.concurrency,
      activeRenders,
      availableParallelism(),
    );
    const useGpu = !transparent && remotionHardwareEncodingAvailable();

    const { cancelSignal, cancel } = makeCancelSignal();
    opts.signal?.addEventListener('abort', cancel, { once: true });
    const render = (gpu: boolean): ReturnType<typeof renderMedia> =>
      renderMedia({
        serveUrl,
        cancelSignal,
        concurrency,
        puppeteerInstance,
        composition: {
          ...composition,
          durationInFrames,
          fps: opts.fps,
          width: opts.width,
          height: opts.height,
        },
        codec: transparent ? 'prores' : 'h264',
        proResProfile: transparent ? '4444' : undefined,
        // ProRes defaults to yuv420p (no alpha). Without an alpha-carrying pixel
        // format the "transparent" areas bake to black and composite as a black
        // screen behind the overlay. yuva444p10le is the alpha-capable ProRes 4444
        // format; paired with the PNG image format this preserves the alpha channel.
        pixelFormat: transparent ? 'yuva444p10le' : undefined,
        outputLocation: outPath,
        overwrite: true,
        inputProps: opts.inputProps,
        imageFormat: transparent ? 'png' : 'jpeg',
        jpegQuality: transparent ? undefined : OPAQUE_JPEG_QUALITY,
        hardwareAcceleration: gpu ? 'if-possible' : 'disable',
        videoBitrate: gpu ? OPAQUE_GPU_BITRATE : undefined,
        chromiumOptions: CHROMIUM_OPTIONS,
        binariesDirectory,
        // Forward Remotion's per-frame progress (0..1) so block segments advance
        // the render bar smoothly rather than stalling for the whole encode. The
        // wrapper is always defined (no-ops via optional chaining when the caller
        // passed nothing) to stay clean under exactOptionalPropertyTypes.
        onProgress: ({ progress }) => opts.onProgress?.(progress),
      });
    try {
      opts.signal?.throwIfAborted();
      try {
        await render(useGpu);
      } catch (err) {
        if (!useGpu || opts.signal?.aborted) throw err;
        console.warn('[Remotion] GPU encode failed, retrying on CPU:', err);
        await render(false);
      }
      opts.signal?.throwIfAborted();
    } finally {
      opts.signal?.removeEventListener('abort', cancel);
    }

    console.log(
      `[Remotion] ${opts.compositionId} rendered ${durationInFrames}f ` +
        `${opts.width}x${opts.height} concurrency=${concurrency} gpu=${useGpu} ` +
        `in ${Date.now() - started}ms`,
    );
    if (cacheDir && cacheKey) {
      try {
        storeCachedRender(cacheDir, cacheKey, outPath);
        pruneRenderCache(cacheDir, DEFAULT_RENDER_CACHE_MAX_BYTES);
      } catch (err) {
        console.warn('[Remotion] could not store render in cache:', err);
      }
    }
    return outPath;
  } finally {
    activeRenders--;
    scheduleIdleBrowserClose();
  }
}
