import type { ExplanationVisualMode } from '../diagrams/types';
import type {
  BusinessAssetId,
  BusinessKind,
  BusinessPack,
  BusinessRecipe,
  BusinessRecipeId,
  BusinessTreatmentId,
} from './types';

const BOTH: readonly ExplanationVisualMode[] = ['diagram', 'hybrid'];
const DIAGRAM: readonly ExplanationVisualMode[] = ['diagram'];

export const BUSINESS_KIND_OWNERS = {
  'task-map': 'work',
  'coordination-map': 'work',
  'work-redesign': 'work',
  'delegation-scope': 'authority',
  'authority-handoff': 'authority',
  'constraint-check': 'authority',
  'business-blueprint': 'commercial',
  'business-replication': 'commercial',
  'organization-map': 'organization',
  'system-reconciliation': 'organization',
  'operating-cost': 'economics',
  'scale-economics': 'economics',
  'value-capture': 'economics',
  'market-dependency': 'markets',
  'procurement-commitment': 'markets',
  'fund-lifecycle': 'funds',
  'distribution-waterfall': 'funds',
  'fund-liquidity': 'funds',
  'economic-rights': 'capital',
  'capital-structure': 'capital',
  'investment-outcomes': 'capital',
  'capacity-map': 'infrastructure',
  'operating-lineage': 'infrastructure',
  'staged-decision': 'decisions',
  'measurement-frame': 'decisions',
  'uncertainty-album': 'decisions',
} as const satisfies Record<BusinessKind, BusinessPack>;

/** Metadata only: this does not select a renderer or relax any source parser. */
function recipe(
  id: BusinessRecipeId,
  kind: BusinessRecipe['kind'],
  preset: string,
  owner: BusinessPack,
  objective: string,
  sourceRequirements: readonly string[],
  assets: readonly BusinessAssetId[],
  treatments: readonly BusinessTreatmentId[],
  modes: readonly ExplanationVisualMode[] = BOTH,
): BusinessRecipe {
  return {
    id,
    kind,
    preset,
    owner,
    objective,
    sourceRequirements,
    modes,
    assets,
    treatments,
    fixtureIds: [`business-${id}`],
  };
}

export const BUSINESS_RECIPES: readonly BusinessRecipe[] = [
  recipe(
    'OP-01',
    'task-map',
    'task-split',
    'work',
    'Task atlas',
    ['Named job, distinct child tasks, retained task identities and stated task ownership'],
    ['A-04'],
    ['M-01'],
  ),
  recipe(
    'OP-02',
    'task-map',
    'capability-boundary',
    'work',
    'Capability frontier',
    [
      'Named task capability and explicit tested, unavailable or unknown boundary; capability is not permission',
    ],
    [],
    ['M-03'],
    DIAGRAM,
  ),
  recipe(
    'OP-03',
    'coordination-map',
    'cross-function',
    'work',
    'Cross-functional team',
    ['Distinct source-named roles and a supported handoff; no inferred team members'],
    ['A-04'],
    ['M-09'],
  ),
  recipe(
    'OP-04',
    'task-map',
    'responsibility',
    'work',
    'Responsibility map',
    ['Explicit performer, approver and accountable owner for each supported task'],
    ['A-04'],
    ['M-01'],
  ),
  recipe(
    'OP-05',
    'work-redesign',
    'expertise-transfer',
    'work',
    'Expert-to-playbook',
    [
      'Expert, source evidence, approved playbook revision and stated later use; no retraining claim',
    ],
    ['A-07'],
    ['M-11'],
  ),
  recipe(
    'OP-06',
    'work-redesign',
    'redeployment',
    'work',
    'Workforce redeployment',
    [
      'Source-stated before/after task allocation with unchanged actor identity; no invented job loss',
    ],
    ['A-02'],
    ['M-01'],
  ),
  recipe(
    'OP-07',
    'coordination-map',
    'supervised-fanout',
    'work',
    'Supervisor fan-out',
    ['Source-stated supervisor/delegate links and explicit review limits or unknown capacity'],
    ['A-08'],
    ['M-03'],
  ),
  recipe(
    'OP-08',
    'coordination-map',
    'handoff-load',
    'work',
    'Coordination load',
    ['Supported handoffs and any measured load with its unit and period'],
    ['A-04'],
    ['M-09'],
  ),
  recipe(
    'OP-09',
    'delegation-scope',
    'permissions',
    'authority',
    'Permission passport',
    ['Actor, allowed and denied actions, source-stated scope, expiry or explicit unknown'],
    ['A-05'],
    ['M-03'],
  ),
  recipe(
    'OP-10',
    'agent-workflow',
    'approval-gate',
    'authority',
    'Approval gate',
    ['Existing approval-gate source conditions, pending/denied/approved state and unchanged truth'],
    ['A-06'],
    ['M-09'],
  ),
  recipe(
    'OP-11',
    'delegation-scope',
    'action-limits',
    'authority',
    'Bounded autonomy',
    ['Delegate, action, explicit limits and condition; no access inferred from skill'],
    ['A-05'],
    ['M-12'],
  ),
  recipe(
    'OP-12',
    'authority-handoff',
    'exception-review',
    'authority',
    'Exception economy',
    ['Exception, supported review path, exact costs if supplied; no duplicate retry/review cost'],
    ['A-08'],
    ['M-09'],
  ),
  recipe(
    'OP-13',
    'authority-handoff',
    'declared-audit-chain',
    'authority',
    'Audit trail',
    ['Named declared audit events, actor and revision evidence; not live monitoring'],
    ['A-07'],
    ['M-11'],
  ),
  recipe(
    'OP-14',
    'authority-handoff',
    'action-consequences',
    'authority',
    'Reversible/irreversible actions',
    ['Source-stated action, reversibility and consequences; no implied legal conclusion'],
    ['A-06'],
    ['M-12'],
  ),
  recipe(
    'OP-15',
    'authority-handoff',
    'accountable-transfer',
    'authority',
    'Accountable handoffs',
    ['Explicit performer, approver, accountable owner and pending/accepted transfer'],
    ['A-06'],
    ['M-09'],
  ),
  recipe(
    'OP-16',
    'constraint-check',
    'conflicting-limits',
    'authority',
    'Constraint collision',
    ['Two locally bound incompatible requirements and explicit unresolved state'],
    [],
    ['M-03'],
    DIAGRAM,
  ),
  recipe(
    'OP-17',
    'business-blueprint',
    'back-office',
    'commercial',
    'Storefront cutaway',
    ['Same named business, customer-facing service and supported internal task links'],
    ['A-01', 'A-04'],
    ['M-04'],
  ),
  recipe(
    'OP-18',
    'work-redesign',
    'owner-playbook',
    'work',
    'Owner knowledge handoff',
    ['Owner, source record, approved playbook revision and stated receiving performer'],
    ['A-07'],
    ['M-11'],
  ),
  recipe(
    'OP-19',
    'business-blueprint',
    'service-slots',
    'commercial',
    'Appointment capacity',
    ['Source-stated service slots, period and distinct reserved/used/available states'],
    ['A-02'],
    ['M-12'],
  ),
  recipe(
    'OP-20',
    'business-blueprint',
    'service-lifecycle',
    'commercial',
    'Lead to book to deliver',
    ['Named lead, booking and delivery stages with explicit pending/observed states'],
    ['A-02', 'A-04'],
    ['M-09'],
  ),
  recipe(
    'OP-21',
    'business-blueprint',
    'owner-dependency',
    'commercial',
    'Founder dependency',
    ['Explicit owner-dependent task; dependency removal only if source supports it'],
    ['A-01'],
    ['M-12'],
  ),
  recipe(
    'OP-22',
    'business-blueprint',
    'service-modules',
    'commercial',
    'Productized service',
    ['Named service modules, compatibility and any bounded repeated offering'],
    ['A-02'],
    ['M-01'],
  ),
  recipe(
    'OP-23',
    'business-replication',
    'shared-standard-local-context',
    'commercial',
    'Micro-franchise replication',
    ['Distinct local units, source-stated shared standard and local differences'],
    ['A-03'],
    ['M-07'],
  ),
  recipe(
    'OP-24',
    'market-dependency',
    'channel-concentration',
    'markets',
    'Channel dependence',
    ['Supported business/channel dependence; stated denominator for any concentration'],
    ['A-01'],
    ['M-03'],
  ),
  recipe(
    'OP-25',
    'organization-map',
    'federated-units',
    'organization',
    'Federated pods',
    ['Distinct named units with explicit local/shared responsibilities'],
    ['A-03'],
    ['M-07'],
  ),
  recipe(
    'OP-26',
    'organization-map',
    'decision-rights',
    'organization',
    'Central/local decisions',
    ['Named decisions and explicit local/central authority and escalation'],
    ['A-03', 'A-05'],
    ['M-09'],
  ),
  recipe(
    'OP-27',
    'organization-map',
    'rollout-rings',
    'organization',
    'Controlled rollout',
    ['Stated unit groups and configured/observed rollout states; not software deployment'],
    ['A-03'],
    ['M-06'],
  ),
  recipe(
    'OP-28',
    'organization-map',
    'legacy-boundaries',
    'organization',
    'Brownfield integration',
    ['Source-named old/new systems, interface and unsupported or unresolved boundary'],
    ['A-16'],
    ['M-03'],
  ),
  recipe(
    'OP-29',
    'system-reconciliation',
    'merge-identities',
    'organization',
    'Merger reconciliation',
    ['Explicit record identities and matched/unresolved status; no invented matching'],
    ['A-04'],
    ['M-11'],
  ),
  recipe(
    'OP-30',
    'organization-map',
    'stated-chargeback',
    'organization',
    'Shared-service chargeback',
    ['Source-stated payer, service, period and exact one-currency allocations/remainder'],
    ['A-03'],
    ['M-02'],
  ),
  recipe(
    'OP-31',
    'organization-map',
    'declared-tool-boundaries',
    'organization',
    'Shadow AI',
    ['Source-declared allowed/unapproved tools; illustrative, not monitoring'],
    [],
    ['M-03'],
    DIAGRAM,
  ),
  recipe(
    'OP-32',
    'coordination-map',
    'approval-load',
    'work',
    'Approval congestion',
    ['Named review queue, reviewer and observed/pending load with supported capacity'],
    ['A-06', 'A-08'],
    ['M-09'],
  ),
  recipe(
    'OP-33',
    'operating-cost',
    'per-outcome',
    'economics',
    'Cost of resolved task',
    ['Exact stated cost parts, resolved-outcome denominator, period and no double counting'],
    ['A-04'],
    ['M-02'],
  ),
  recipe(
    'OP-34',
    'scale-economics',
    'fixed-variable',
    'economics',
    'Fixed/marginal costs',
    ['Explicit fixed/variable bases and supported samples; no extrapolated cost curve'],
    ['A-02'],
    ['M-02'],
  ),
  recipe(
    'OP-35',
    'capacity-map',
    'installed-used-reserved',
    'infrastructure',
    'Capacity utilization',
    ['Installed, used and reserved same-unit capacity for one period; no overlap invention'],
    ['A-13'],
    ['M-12'],
  ),
  recipe(
    'OP-36',
    'scale-economics',
    'output-staffing',
    'economics',
    'Hiring frontier',
    ['Source output/staffing samples with explicit task and period; no hiring forecast'],
    ['A-02'],
    ['M-08'],
  ),
  recipe(
    'OP-37',
    'operating-cost',
    'implementation-periods',
    'economics',
    'Implementation valley',
    ['Source-period implementation costs and stated observations; no guaranteed payback'],
    ['A-07'],
    ['M-06'],
  ),
  recipe(
    'OP-38',
    'operating-cost',
    'comparable-pricing-bases',
    'economics',
    'Pricing models',
    ['Explicit seat/token/outcome denominators; incomparable prices remain separate'],
    [],
    ['M-08'],
    DIAGRAM,
  ),
  recipe(
    'OP-39',
    'value-capture',
    'source-stated-allocation',
    'economics',
    'Value-capture chain',
    ['Source-stated actor allocations and retained remainder in exact same-currency amounts'],
    ['A-10'],
    ['M-02'],
  ),
  recipe(
    'OP-40',
    'operating-cost',
    'accounting-bases',
    'economics',
    'Revenue/profit/cash',
    ['Distinct source-stated revenue, profit and cash bases/periods; no inferred expenses'],
    ['A-04'],
    ['M-02'],
  ),
  recipe(
    'OP-41',
    'market-dependency',
    'demand-access',
    'markets',
    'Distribution/production',
    ['Source production and demand/channel access links, not assumed customer demand'],
    ['A-01'],
    ['M-03'],
  ),
  recipe(
    'OP-42',
    'market-dependency',
    'migration-constraints',
    'markets',
    'Switching friction',
    ['Explicit migration dependencies and preserved conditional/unknown exit state'],
    ['A-16'],
    ['M-12'],
  ),
  recipe(
    'OP-43',
    'market-dependency',
    'participation-matching',
    'markets',
    'Two-sided cold start',
    ['Named sides and explicit participation/matching conditions; no invented transactions'],
    ['A-02'],
    ['M-09'],
  ),
  recipe(
    'OP-44',
    'market-dependency',
    'stated-participation-benefit',
    'markets',
    'Network effects',
    ['Explicit source-stated participation benefit; connections alone do not establish it'],
    [],
    ['M-03'],
    DIAGRAM,
  ),
  recipe(
    'OP-45',
    'market-dependency',
    'differentiated-offering',
    'markets',
    'Commoditization/differentiation',
    ['Source-named comparable offering and stated differentiator; no implied winner'],
    ['A-01'],
    ['M-08'],
  ),
  recipe(
    'OP-46',
    'market-dependency',
    'supplier-distribution-boundaries',
    'markets',
    'Platform/supplier dependence',
    ['Named supplier, platform and distribution dependencies with stated boundaries'],
    ['A-16'],
    ['M-03'],
  ),
  recipe(
    'OP-47',
    'procurement-commitment',
    'request-quote-authorize-pay',
    'markets',
    'Agent purchasing',
    ['Distinct request, quotation, permission and actual payment; promises are not cash'],
    ['A-05', 'A-06'],
    ['M-09'],
  ),
  recipe(
    'OP-48',
    'market-dependency',
    'complementary-specialists',
    'markets',
    'Niche complementarity',
    ['Named specialist roles and explicit complementary relationships'],
    ['A-02'],
    ['M-07'],
  ),
  recipe(
    'OP-49',
    'fund-lifecycle',
    'capital-states',
    'funds',
    'Commit to call to invest',
    [
      'Distinct source-stated commitment, call, contribution and deployment; exact cash conservation',
    ],
    ['A-09'],
    ['M-10'],
  ),
  recipe(
    'OP-50',
    'fund-lifecycle',
    'subscriptions-and-close',
    'funds',
    'Closing/uncalled commitments',
    ['Source closing event, subscriptions and uncalled commitment; no promised cash availability'],
    ['A-09'],
    ['M-03'],
  ),
  recipe(
    'OP-51',
    'distribution-waterfall',
    'stated-priority-tiers',
    'funds',
    'Distribution waterfall',
    ['Source-specific priority order, ceilings, partial tiers and retained cash; no default terms'],
    ['A-10'],
    ['M-10'],
  ),
  recipe(
    'OP-52',
    'distribution-waterfall',
    'gross-to-net',
    'funds',
    'Fees/gross/net',
    ['Exact source-stated gross, costs and net with compatible periods and explicit remainders'],
    [],
    ['M-02'],
    DIAGRAM,
  ),
  recipe(
    'OP-53',
    'fund-lifecycle',
    'source-periods',
    'funds',
    'Vintage/fund lifecycle',
    ['Explicit source dates/periods and capital states; dates do not become beat clocks'],
    ['A-09'],
    ['M-06'],
  ),
  recipe(
    'OP-54',
    'fund-lifecycle',
    'retained-follow-on-capital',
    'funds',
    'Follow-on reserves',
    ['Explicit retained cash and source-stated follow-on allocation; no invented future return'],
    ['A-09', 'A-10'],
    ['M-12'],
  ),
  recipe(
    'OP-55',
    'fund-liquidity',
    'periodic-repurchase',
    'funds',
    'Interval-fund repurchases',
    [
      'Explicit interval fund, stated window/cap and pending/fulfilled requests; no guaranteed exit',
    ],
    ['A-09', 'A-08'],
    ['M-12'],
  ),
  recipe(
    'OP-56',
    'fund-liquidity',
    'valuation-cash-distinction',
    'funds',
    'NAV/cash',
    [
      'Stated valuation and available cash as distinct bases; valuation is not redemption liquidity',
    ],
    ['A-12'],
    ['M-03'],
  ),
  recipe(
    'OP-57',
    'economic-rights',
    'ownership-versus-claims',
    'capital',
    'Economic-rights X-ray',
    ['Separate shares, control, claims and source-supported/unknown payout priority'],
    ['A-12'],
    ['M-04'],
  ),
  recipe(
    'OP-58',
    'portfolio-exposure',
    'shared-driver',
    'capital',
    'Shared dependency lens',
    ['Existing qualitative shared-driver evidence; no fabricated correlation or numeric risk'],
    ['A-12'],
    ['M-03'],
  ),
  recipe(
    'OP-59',
    'investment-outcomes',
    'source-outcome-set',
    'capital',
    'Outcome dispersion',
    ['Bounded source financial outcome samples, reporting basis and stated probabilities only'],
    [],
    ['M-08'],
    DIAGRAM,
  ),
  recipe(
    'OP-60',
    'capital-structure',
    'conditional-rounds',
    'capital',
    'Staged financing',
    ['Explicit financing conditions and supported share issuance arithmetic/denominators'],
    ['A-09', 'A-12'],
    ['M-12'],
  ),
  recipe(
    'OP-61',
    'capital-structure',
    'financing-versus-capacity',
    'capital',
    'Infrastructure debt',
    ['Named financing obligation and distinct physical resource readiness; no inferred capacity'],
    ['A-11', 'A-13'],
    ['M-03'],
  ),
  recipe(
    'OP-62',
    'capital-structure',
    'obligations-and-maturity',
    'capital',
    'Maturity/duration mismatch',
    ['Source maturity dates, amounts and asset duration/liquidity distinctions'],
    ['A-11'],
    ['M-06'],
  ),
  recipe(
    'OP-63',
    'operating-lineage',
    'evidence-and-missing-information',
    'infrastructure',
    'Diligence evidence room',
    ['Explicit evidence items, versions, periods and missing facts; not a diligence conclusion'],
    ['A-07'],
    ['M-11'],
  ),
  recipe(
    'OP-64',
    'economic-rights',
    'claim-asset-distinction',
    'capital',
    'Transferable claim/illiquid asset',
    ['Source transferability and distinct underlying liquidity or unresolved liquidity'],
    ['A-12'],
    ['M-03'],
  ),
  recipe(
    'OP-65',
    'capacity-map',
    'physical-readiness',
    'infrastructure',
    'Money-ready/power-not-ready',
    ['Explicit financing, power and cooling readiness conditions; no inferred commissioning'],
    ['A-13', 'A-14', 'A-15'],
    ['M-12'],
  ),
  recipe(
    'OP-66',
    'capacity-map',
    'bounded-request-capacity',
    'infrastructure',
    'Inference queue',
    ['Stated bounded request load/capacity with same unit and period or qualitative queue'],
    ['A-13'],
    ['M-12'],
  ),
  recipe(
    'OP-67',
    'capacity-map',
    'resource-states',
    'infrastructure',
    'Idle/reserved/burst',
    ['Source-stated idle/reserved/burst states with nonoverlapping compatible quantities'],
    ['A-13', 'A-15'],
    ['M-12'],
  ),
  recipe(
    'OP-68',
    'capacity-map',
    'declared-processing-scope',
    'infrastructure',
    'Data residency',
    ['Explicit named processing boundary; illustration is not compliance or monitoring'],
    ['A-16'],
    ['M-03'],
  ),
  recipe(
    'OP-69',
    'operating-lineage',
    'provider-transition',
    'infrastructure',
    'Provider exit',
    ['Named providers and source-stated dependency transition, pending/blocked/complete state'],
    ['A-16'],
    ['M-09'],
  ),
  recipe(
    'OP-70',
    'operating-lineage',
    'versioned-provenance',
    'infrastructure',
    'Data lineage',
    ['Stable source/version identities and locally bound declared provenance edges'],
    ['A-07', 'A-16'],
    ['M-11'],
  ),
  recipe(
    'OP-71',
    'operating-lineage',
    'evaluation-periods',
    'infrastructure',
    'Model drift',
    ['Source evaluation periods and comparable task/population metrics; no implied live drift'],
    [],
    ['M-06'],
    DIAGRAM,
  ),
  recipe(
    'OP-72',
    'capacity-map',
    'end-to-end-periods',
    'infrastructure',
    'Latency accumulation',
    ['Source component/end-to-end latencies with same period/unit and no duplicated duration'],
    ['A-16'],
    ['M-02'],
  ),
  recipe(
    'OP-73',
    'staged-decision',
    'contingent-commitment',
    'decisions',
    'Real options/stage gates',
    ['Source commitments, contingent gate and preserved unknown future; no calculated valuation'],
    ['A-09', 'A-06'],
    ['M-12'],
  ),
  recipe(
    'OP-74',
    'constraint-check',
    'dated-conditions',
    'authority',
    'Commitment calendar',
    [
      'Source dates and explicit compatible/conflicting/unresolved conditions; no legal interpretation',
    ],
    ['A-11'],
    ['M-03'],
  ),
  recipe(
    'OP-75',
    'possible-futures',
    'branching-scenarios',
    'decisions',
    'Alternative designs',
    ['Existing conditional alternatives, same baseline and unresolved comparison; no winner'],
    ['A-03'],
    ['M-08'],
  ),
  recipe(
    'OP-76',
    'measurement-frame',
    'planned-observed',
    'decisions',
    'Plan/observed variance',
    [
      'Distinct configured/planned and observed values with same subject, unit, period and denominator',
    ],
    ['A-04'],
    ['M-05'],
  ),
  recipe(
    'OP-77',
    'measurement-frame',
    'firms-functions-workers',
    'decisions',
    'Adoption denominators',
    ['Explicit firm/function/worker populations and denominators; no mixed-population comparison'],
    ['A-03'],
    ['M-07'],
  ),
  recipe(
    'OP-78',
    'measurement-frame',
    'original-and-surviving-cohorts',
    'decisions',
    'Survivorship',
    ['Source original cohort, surviving cohort, attrition and matched outcome basis'],
    ['A-04'],
    ['M-08'],
  ),
  recipe(
    'OP-79',
    'uncertainty-album',
    'alternatives-or-source-distribution',
    'decisions',
    'Outcome album',
    [
      'Bounded supplied alternatives/outcomes; probabilities only when supported; equal qualitative area/time',
    ],
    ['A-03'],
    ['M-08'],
  ),
  recipe(
    'OP-80',
    'coordination-map',
    'bottleneck-shift',
    'work',
    'Bottleneck migration',
    ['Explicit before/after constraints and task identities; no invented throughput improvement'],
    ['A-02', 'A-06'],
    ['M-12'],
  ),
];

export function businessRecipe(kind: string, preset: string): BusinessRecipe | null {
  return BUSINESS_RECIPES.find((entry) => entry.kind === kind && entry.preset === preset) ?? null;
}

export function businessModeAllowed(
  kind: string,
  preset: string,
  mode: ExplanationVisualMode,
): boolean {
  return businessRecipe(kind, preset)?.modes.includes(mode) ?? false;
}
